# Generated by Django 5.0.6 on 2024-07-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "quantity_in_stock",
                    models.DecimalField(decimal_places=0, max_digits=5),
                ),
                ("reorder_level", models.SmallIntegerField()),
                ("expiry_date", models.DateField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "product_table",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_in_stock__gte", 0)),
                name="product_table_quantity_in_stock_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("reorder_level__gte", 0)),
                name="product_table_reorder_level_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)),
                name="product_table_unit_price_check",
            ),
        ),
    ]
