# Generated by Django 5.0.6 on 2024-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_category_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
