# Generated by Django 5.0.6 on 2024-07-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_tag_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="product.tag"
            ),
        ),
    ]
