# Generated by Django 5.0.6 on 2024-07-16 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="description",
        ),
    ]
