# Generated by Django 5.0.6 on 2024-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "supplier_table",
            },
        ),
    ]
