# Generated by Django 5.0.6 on 2024-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="supplier_id",
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
